% This program is generated by zGeneratePlotHydrogen.m
% based on the Excel file H_bonding_Atoms_from_Isostericity_Table.xls
% created by Jesse Stombaugh.
% [X,Y]=zHydrogenLocations(NT1,NT2,Class) returns the locations of the atoms
% corresponding to hydrogen bonds
%
%
function [X,Y] = zHydrogenLocations(NT1,NT2,Class)

Paircode = 4*(NT2.Code-1) + NT1.Code;
switch Paircode
  case {2, 3, 4, 8, 10, 12},
    N1 = NT2;
    N2 = NT1;
  otherwise
    N1 = NT1;
    N2 = NT2;
end
Paircode = 4*(N2.Code-1) + N1.Code;

if (Class == 1) & (Paircode == 1),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 1) & (Paircode == 5),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 1) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(12,:);
elseif (Class == 1) & (Paircode == 13),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Fit(11,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -1) & (Paircode == 5),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 1) & (Paircode == 6),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 1) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(4,:);
  X(3,:) = N1.Fit(16,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == 1) & (Paircode == 14),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -1) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(12,:);
elseif (Class == -1) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(4,:);
  X(3,:) = N1.Fit(16,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == 1) & (Paircode == 15),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -1) & (Paircode == 13),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Fit(11,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -1) & (Paircode == 14),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == -1) & (Paircode == 15),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 1) & (Paircode == 16),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 2) & (Paircode == 1),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(14,:);
elseif (Class == 2) & (Paircode == 5),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == 2) & (Paircode == 13),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Fit(11,:);
  Y(3,:) = N2.Fit(6,:);
elseif (Class == -2) & (Paircode == 5),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(14,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 2) & (Paircode == 6),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == 2) & (Paircode == 7),
  X(1,:) = N1.Fit(16,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 2) & (Paircode == 14),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == -2) & (Paircode == 7),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 2) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == 2) & (Paircode == 15),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == -2) & (Paircode == 13),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Fit(14,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -2) & (Paircode == 14),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -2) & (Paircode == 15),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(6,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 2) & (Paircode == 16),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == 3) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(10,:);
elseif (Class == 3) & (Paircode == 13),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(9,:);
elseif (Class == 3) & (Paircode == 6),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 3) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(10,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 3) & (Paircode == 14),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(9,:);
elseif (Class == -3) & (Paircode == 9),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(10,:);
  Y(2,:) = N2.Fit(12,:);
elseif (Class == 3) & (Paircode == 11),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Fit(10,:);
elseif (Class == -3) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(10,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Fit(12,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -3) & (Paircode == 15),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 3) & (Paircode == 16),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(9,:);
elseif (Class == 4) & (Paircode == 1),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(10,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(15,:);
elseif (Class == 4) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(10,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == -4) & (Paircode == 5),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 4) & (Paircode == 6),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(12,:);
elseif (Class == 4) & (Paircode == 7),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(6,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 4) & (Paircode == 11),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(10,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == 4) & (Paircode == 15),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(9,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == -4) & (Paircode == 13),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -4) & (Paircode == 15),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(10,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 4) & (Paircode == 16),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(9,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == 5) & (Paircode == 1),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 5),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 13),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == -5) & (Paircode == 5),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 5) & (Paircode == 6),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 7),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(4,:);
elseif (Class == 5) & (Paircode == 14),
  X(1,:) = N1.Fit(13,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == -5) & (Paircode == 9),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(12,:);
  X(3,:) = N1.Sugar(3,:);
  Y(3,:) = N2.Fit(16,:);
elseif (Class == -5) & (Paircode == 7),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(15,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 5) & (Paircode == 15),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == -5) & (Paircode == 13),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(11,:);
  X(3,:) = N1.Sugar(3,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -5) & (Paircode == 14),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -5) & (Paircode == 15),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 5) & (Paircode == 16),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 6) & (Paircode == 1),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == 6) & (Paircode == 5),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(14,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 6) & (Paircode == 9),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(15,:);
elseif (Class == 6) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(14,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -6) & (Paircode == 5),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == 6) & (Paircode == 6),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 6) & (Paircode == 7),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(13,:);
  X(3,:) = N1.Fit(15,:);
  Y(3,:) = N2.Fit(4,:);
elseif (Class == 6) & (Paircode == 14),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -6) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 6) & (Paircode == 15),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(12,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -6) & (Paircode == 13),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -6) & (Paircode == 14),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(11,:);
elseif (Class == -6) & (Paircode == 15),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == 6) & (Paircode == 16),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 7) & (Paircode == 9),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 7) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(10,:);
elseif (Class == -7) & (Paircode == 9),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -7) & (Paircode == 7),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(10,:);
elseif (Class == 7) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(13,:);
elseif (Class == 8) & (Paircode == 1),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(15,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(10,:);
elseif (Class == 8) & (Paircode == 5),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 8) & (Paircode == 9),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 8) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -8) & (Paircode == 5),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 8) & (Paircode == 7),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 8) & (Paircode == 14),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -8) & (Paircode == 9),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -8) & (Paircode == 7),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 8) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(13,:);
elseif (Class == -8) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -8) & (Paircode == 14),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 9) & (Paircode == 1),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == 9) & (Paircode == 5),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == 9) & (Paircode == 9),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(15,:);
elseif (Class == 9) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == -9) & (Paircode == 5),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 9) & (Paircode == 6),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(10,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 9) & (Paircode == 7),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(12,:);
elseif (Class == 9) & (Paircode == 14),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == -9) & (Paircode == 9),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 9) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(15,:);
elseif (Class == -9) & (Paircode == 13),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -9) & (Paircode == 14),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(9,:);
elseif (Class == -9) & (Paircode == 15),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 9) & (Paircode == 16),
  X(1,:) = N1.Fit(9,:);
  Y(1,:) = N2.Fit(3,:);
elseif (Class == 10) & (Paircode == 1),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(14,:);
  Y(3,:) = N2.Sugar(3,:);
elseif (Class == 10) & (Paircode == 5),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(14,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 10) & (Paircode == 9),
  X(1,:) = N1.Fit(10,:);
  Y(1,:) = N2.Fit(15,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 10) & (Paircode == 13),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(14,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == -10) & (Paircode == 5),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == 10) & (Paircode == 6),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 10) & (Paircode == 14),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(13,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 10) & (Paircode == 11),
  X(1,:) = N1.Fit(6,:);
  Y(1,:) = N2.Fit(15,:);
elseif (Class == -10) & (Paircode == 13),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == -10) & (Paircode == 15),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(6,:);
elseif (Class == 11) & (Paircode == 1),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(3,:);
  Y(3,:) = N2.Fit(11,:);
elseif (Class == 11) & (Paircode == 5),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 11) & (Paircode == 9),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(3,:);
  Y(3,:) = N2.Fit(15,:);
elseif (Class == 11) & (Paircode == 13),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -11) & (Paircode == 5),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 11) & (Paircode == 6),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 11) & (Paircode == 7),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
  X(3,:) = N1.Fit(15,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == 11) & (Paircode == 14),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -11) & (Paircode == 9),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
  X(3,:) = N1.Fit(11,:);
  Y(3,:) = N2.Fit(3,:);
  X(4,:) = N1.Fit(4,:);
  Y(4,:) = N2.Fit(15,:);
elseif (Class == -11) & (Paircode == 7),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 11) & (Paircode == 11),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(3,:);
  Y(3,:) = N2.Fit(15,:);
elseif (Class == 11) & (Paircode == 15),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -11) & (Paircode == 13),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
  X(3,:) = N1.Fit(11,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == -11) & (Paircode == 14),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == -11) & (Paircode == 15),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Sugar(3,:);
  X(3,:) = N1.Fit(15,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == 11) & (Paircode == 16),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Sugar(3,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 12) & (Paircode == 1),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(11,:);
  X(2,:) = N1.Fit(9,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(4,:);
  Y(3,:) = N2.Sugar(3,:);
elseif (Class == 12) & (Paircode == 5),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 12) & (Paircode == 9),
  X(1,:) = N1.Fit(3,:);
  Y(1,:) = N2.Fit(15,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(3,:);
  X(3,:) = N1.Fit(4,:);
  Y(3,:) = N2.Sugar(3,:);
elseif (Class == 12) & (Paircode == 13),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(11,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == -12) & (Paircode == 9),
  X(1,:) = N1.Fit(11,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(15,:);
  X(3,:) = N1.Sugar(3,:);
  Y(3,:) = N2.Fit(16,:);
elseif (Class == -12) & (Paircode == 7),
  X(1,:) = N1.Fit(15,:);
  Y(1,:) = N2.Fit(3,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Sugar(3,:);
elseif (Class == 12) & (Paircode == 11),
  X(1,:) = N1.Sugar(3,:);
  Y(1,:) = N2.Fit(16,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(15,:);
  X(3,:) = N1.Fit(15,:);
  Y(3,:) = N2.Fit(3,:);
  X(4,:) = N1.Fit(16,:);
  Y(4,:) = N2.Sugar(3,:);
elseif (Class == 12) & (Paircode == 15),
  X(1,:) = N1.Fit(16,:);
  Y(1,:) = N2.Sugar(3,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(3,:);
elseif (Class == 13) & (Paircode == 1),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(14,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(15,:);
elseif (Class == 13) & (Paircode == 5),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(12,:);
  X(2,:) = N1.Fit(4,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == -13) & (Paircode == 5),
  X(1,:) = N1.Fit(14,:);
  Y(1,:) = N2.Fit(4,:);
  X(2,:) = N1.Fit(15,:);
  Y(2,:) = N2.Fit(4,:);
  X(3,:) = N1.Fit(14,:);
  Y(3,:) = N2.Fit(3,:);
elseif (Class == 13) & (Paircode == 6),
  X(1,:) = N1.Fit(4,:);
  Y(1,:) = N2.Fit(13,:);
  X(2,:) = N1.Fit(3,:);
  Y(2,:) = N2.Fit(13,:);
elseif (Class == 13) & (Paircode == 11),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Fit(6,:);
elseif (Class == 13) & (Paircode == 15),
  X(1,:) = N1.Fit(12,:);
  Y(1,:) = N2.Fit(6,:);
  X(2,:) = N1.Fit(16,:);
  Y(2,:) = N2.Fit(6,:);
else
X = [];
Y = [];
end
